name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  async_list_view: ^0.0.1-dev.8
  flutter:
    sdk: flutter
  animations: ^1.1.2
  async: ^2.4.2
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  json_annotation: 3.1.1
  flutter_markdown: ^0.5.1
  provider: ^4.1.0
  either_option: ^1.0.6
  google_fonts: ^1.1.1
  path: ^1.7.0
  universal_html: ^1.2.1
  shared_preferences: ^0.5.12+4
  sqflite: ^2.0.0
  bottom_navy_bar: ^5.6.0
  flag: ^3.2.0
  package_info: ^0.4.3+4
  preload_page_view: ^0.1.4

  cupertino_icons: ^1.0.0
  scrollable_positioned_list: ^0.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: 3.5.1
  firedart: ^0.8.3
  df: ^0.3.0
  sqflite_common_ffi:
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/dictionaryV0_1_0.db
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/r_logo_flat_full.png"
  adaptive_icon_background: "assets/images/r_logo_flat_full.png"
  adaptive_icon_foreground: "assets/images/r_logo_flat_full.png"

flutter_native_splash:
  color: "ffffff"
  android_gravity: fill
  image: "assets/images/r_splash_screen.png"