name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  async_list_view: ^0.0.1-dev.8
  flutter:
    sdk: flutter
  async: ^2.4.2
  cloud_firestore: ^0.14.1+3
  firebase_core: 0.5.0+1
  json_annotation: ^3.1.0
  flutter_markdown: ^0.5.1
  provider: ^4.1.0
  rxdart: ^0.24.1
  google_fonts: ^1.1.1
  path: ^1.7.0
  universal_html: ^1.2.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.0
  bottom_navy_bar: ^5.6.0
  flag: ^3.2.0

  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  firedart: ^0.8.3
  df: ^0.3.0
  sqflite_common_ffi:

flutter:
  uses-material-design: true
  assets:
    - assets/entries.db
    - assets/images/
