name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  async: ^2.5.0
  async_list_view: ^0.0.1-dev.8
  cupertino_icons: ^1.0.3
  feedback: ^2.0.0-beta.0
  firebase_analytics: ^8.1.2
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.7
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.0.0
  google_mobile_ads: ^0.13.3
  http: ^0.13.3
  implicit_navigator:
    path: ../implicit_navigator
  intl: ^0.17.0
  just_audio: ^0.9.7
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  shared_preferences: ^2.0.6
  speech_to_text: ^5.0.0
  sprintf: ^6.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  df: ^0.4.0-nullsafety.0
  firedart: ^0.9.0+1
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/glenn.jpg
    - assets/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/r_logo_flat_full.png"
  adaptive_icon_background: "assets/images/r_logo_flat_full.png"
  adaptive_icon_foreground: "assets/images/r_logo_flat_full.png"

flutter_native_splash:
  color: "ffffff"
  android_gravity: fill
  image: "assets/images/r_splash_screen.png"