name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  async_list_view: ^0.0.1-dev.8
  flutter:
    sdk: flutter
  animations: ^2.0.0
  async: ^2.5.0
  firebase_core: ^1.1.0
  json_annotation: ^4.0.1
  flutter_markdown: ^0.6.1
  provider: ^5.0.0
  google_fonts: ^2.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+3
  package_info: ^2.0.0

  cupertino_icons: ^1.0.3
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  feedback:
    path: '../feedback'
  flutter_email_sender: ^5.0.0
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  firedart: ^0.9.0+1
  df:
    path: '../df'
  sqflite_common_ffi: ^2.0.0
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - assets/dictionaryV0_2_0.db
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/r_logo_flat_full.png"
  adaptive_icon_background: "assets/images/r_logo_flat_full.png"
  adaptive_icon_foreground: "assets/images/r_logo_flat_full.png"

flutter_native_splash:
  color: "ffffff"
  android_gravity: fill
  image: "assets/images/r_splash_screen.png"